x-openclaw-env: &openclaw-env
  HOME: /home/node
  TERM: xterm-256color
  OPENCLAW_HOME: /home/node
  OPENCLAW_STATE_DIR: /home/node/.openclaw
  OPENCLAW_GATEWAY_TOKEN: ${OPENCLAW_GATEWAY_TOKEN:-missing-openclaw-gateway-token-env-var}

services:
  openclaw-onboard:
    build:
      context: .
      dockerfile: Dockerfile
    environment: *openclaw-env
    stdin_open: true
    tty: true
    init: true
    entrypoint: ["bash"]
    restart: "no"
    volumes:
      - ./.openclaw:/home/node/.openclaw

  openclaw-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    environment: *openclaw-env
    init: true
    command: ["openclaw", "gateway", "run", "--bind", "lan", "--port", "18789"]
    ports:
      - "18789:18789"
    restart: unless-stopped
    volumes:
      - ./.openclaw:/home/node/.openclaw

  openclaw-cli:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "service:openclaw-gateway"
    cap_drop:
      - NET_RAW
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    environment:
      <<: *openclaw-env
      BROWSER: echo
    stdin_open: true
    tty: true
    init: true
    depends_on:
      - openclaw-gateway
    entrypoint: ["bash"]
    restart: "no"
    volumes:
      - ./.openclaw:/home/node/.openclaw
